//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

public class EvenFib {
  public int evenFibSum() {
    int a = 0, b = 1;
    int c, sum = 0;
    while (a <= 4000000  && b <= 4000000) {
      c = a + b;
      if (c % 2 == 0) {
        sum = sum + c;
      }
      a = b;
      b = c;
    }
    return sum;
  }

  public static void main(String args[]) {
    EvenFib evenFib = new EvenFib();
    int res = evenFib.evenFibSum();
    System.out.println(res);
  }
}
